export const CONTROL_SELECTION_ERROR = 'CONTROL_SELECTION_ERROR';
export const OVERSIZE_DATASET_REQUEST = 'OVERSIZE_DATASET_REQUEST'
export const OVERSIZE_LIST_REQUEST = 'OVERSIZE_LIST_REQUEST'
export const DETAIL_INCORRECT_COUNT = 'DETAIL_INCORRECT_COUNT'
export const DETAIL_NO_VALUE_ENTERED = 'DETAIL_NO_VALUE_ENTERED'
export const NO_DATA_SELECTED = 'NO_DATA_SELECTED'

