export const CONTROL_SELECTION_ERROR = 'CONTROL_SELECTION_ERROR';
export const NO_BUFFER_ID_SELECTED = 'NO_BUFFER_ID_SELECTED'
export const OVERSIZE_DATASET_REQUEST = 'OVERSIZE_DATASET_REQUEST'
export const OVERSIZE_LIST_REQUEST = 'OVERSIZE_LIST_REQUEST'
