# Generated by Django 3.1.2 on 2021-01-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210107_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='pnt',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='occid',
            new_name='ind',
        ),
        migrations.RenameField(
            model_name='tenement',
            old_name='poly',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='tenement',
            old_name='tenid',
            new_name='ind',
        ),
    ]
