# Generated by Django 3.1.2 on 2021-02-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210125_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenementChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=6)),
                ('field', models.CharField(max_length=30)),
                ('lodgedateval', models.DateField(blank=True, null=True)),
                ('startdateval', models.DateField(blank=True, null=True)),
                ('enddateval', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
                ('holderval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holderval_tenement', to='map.tenholder')),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_tenementchange', to='map.tenement')),
                ('majmatval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majmatval_tenement', to='map.material')),
                ('minmatval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minmatval_tenement', to='map.material')),
                ('oidval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oidval_tenement', to='map.tenoriginalid')),
                ('statusval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statusval_tenement', to='map.tenstatus')),
                ('typeval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeval_tenement', to='map.tentype')),
            ],
        ),
    ]
