# Generated by Django 3.1.2 on 2021-02-08 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_occurrenceaddition_occurrencechange_occurrenceremoval_tenementaddition_tenementremoval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencechange',
            name='ind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_change', to='map.occurrence'),
        ),
        migrations.AlterField(
            model_name='tenementchange',
            name='ind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_change', to='map.tenement'),
        ),
    ]
