# Generated by Django 3.1.2 on 2021-02-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20210208_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceaddition',
            name='ind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_addition', to='map.occurrence'),
        ),
        migrations.AlterField(
            model_name='occurrenceremoval',
            name='ind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_inactive', to='map.occurrence'),
        ),
        migrations.AlterField(
            model_name='tenementaddition',
            name='ind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_addition', to='map.tenement'),
        ),
        migrations.AlterField(
            model_name='tenementremoval',
            name='ind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_inactive', to='map.tenement'),
        ),
    ]
